### ISSUE TITLE
sir demo is not working and also when i am compling offline.py i am getting following error

### ISSUE THREAD

**Issue by anshul12112** [matsui528/nanosearch#8]
sir demo is not working and also when i am compling offline.py i am getting following error
![desk](https://user-images.githubusercontent.com/44797619/48839054-3b512200-edb0-11e8-8160-3e0effd3402b.png)

**Comment by anshul12112** [comment]
please resolve this issue as soon as possible i really need this code

**Comment by matsui528** [comment]
Sis is not supported in windows

**Comment by xxllp** [comment]
666，I would like to make it with faiss

**Comment by matsui528** [comment]
Indeed that's possible. You can replace the search part with faiss. But you must use the anaconda environment to install faiss. Because I'd like to make this repo as simple as possible, I keep the current simple nearest neighbor search implementation.

**Comment by xxllp** [comment]
I also want to kown the different  between  cnn feature  and  sift   of   an image

**Comment by matsui528** [comment]
Typically a CNN feature is extracted from an image, e.g., 4096D VGG feature per image. Given a query, the search is conducted by finding similar CNN features.

On the other hand, SIFT is a "local" feature. Several SIFT features are extracted from an image. They are then aggregated into one new feature vector (e.g., BoF vector). The search is done over these aggregated vectors.

CNN features are usually more powerful. So if your purpose is just search, you can simply use CNN features. From a programming point of view, CNN is easier to use because one feature is extracted from one image.

See a survey for more details https://arxiv.org/abs/1608.01807
